version: "3"
services:
  db:
    # RDSでぱっとつかえるのが8.0なので揃える
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: "Asia/Tokyo"
      # 4byteのマルチバイト文字を扱えるcharacter set / 日本語用のひらがなとカタカナを区別するcollation
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_ja_0900_as_cs_ks

  web:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./awesome-django-project:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
