services:
  web:
    build:
      dockerfile: nginx/Dockerfile
    # staticファイルの配信をnginxから行うため、ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./awesome-django-project/static:/static
    ports:
      - "80:80"
    # 先にappを起動してからwebを起動する
    depends_on:
      - app
