name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  # terraformでのタスク定義の記述と一致する必要がある
  AWS_REGION: us-east-1
  ECR_REPOSITORY: django-playground
  ECS_CLUSTER: djangoPlayground-dev
  ECS_SERVICE: djangoPlayground-dev-app
  TASK_DEFINITION_APP: djangoPlayground-dev-app
  TASK_DEFINITION_MIGRATION: djangoPlayground-dev-migration

  CONTAINER_APP_MAIN: djangoPlayground-dev-app-main
  CONTAINER_MIGRATION_MAIN: djangoPlayground-dev-migration-main

  # 一時的にタスク定義の内容を表現するjsonファイルの名前
  ECS_TASK_DEFINITION_APP: task-definition-app.json
  ECS_TASK_DEFINITION_MIGRATION: task-definition-migration.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      DJANGO_SETTINGS_MODULE: "settings.production"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      ################################# image

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f Dockerfile.prod
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      ################################# static

      - name: deploy static files
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        # noinputの説明
        run: |
          docker run $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG python manage.py collectstatic --noinput

      ################################# migration

      - name: Download task definition for migration
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION_MIGRATION }} --query taskDefinition > ${{ env.ECS_TASK_DEFINITION_MIGRATION }}

      - name: Fill in the new image ID in the Amazon ECS task definition for migration
        id: task-def-migration
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_MIGRATION }}
          container-name: ${{ env.CONTAINER_MIGRATION_MAIN }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition for migration
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def-migration.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Run Amazon ECS to migrate database
        # `run: |`だと各行が別のコマンドとして実行できる
        # 以前はバックスラッシュが使えていたらしいが、いまはつかえないことに注意
        # see: https://docs.github.com/ja/enterprise-cloud@latest/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
        run: |
          LATEST_REVISION=$(aws ecs list-task-definitions --region ${{ env.AWS_REGION }} | jq -r '.taskDefinitionArns[]' | grep ${{ env.TASK_DEFINITION_MIGRATION }} | tail -n1)
          NETWORK_CONFIG=$(aws ecs describe-services --region ${{ env.AWS_REGION }} --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} | jq -r '.services[0].networkConfiguration' | jq -c .)
          aws ecs run-task --region ${{ env.AWS_REGION }} --launch-type FARGATE --cluster '${{ env.ECS_CLUSTER }}' --task-definition $LATEST_REVISION --network-configuration $NETWORK_CONFIG --overrides '{"containerOverrides": [{"name": "${{ env.CONTAINER_MIGRATION_MAIN }}", "command": ["python", "manage.py", "migrate"]}]}'

      ################################# app

      - name: Download task definition for application
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION_APP }} --query taskDefinition > ${{ env.ECS_TASK_DEFINITION_APP }}

      - name: Fill in the new image ID in the Amazon ECS task definition for application
        id: task-def-app
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_APP }}
          container-name: ${{ env.CONTAINER_APP_MAIN }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition for application
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def-app.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
